---
- name: Create an image from os disk
  hosts: localhost #we are calling azure api from the ansible control node
  tasks:
    - name: Calling out to azure to create snapshot
      azure.azcollection.azure_rm_snapshot:
        client_id: '{{ lookup("env", "AZ_CLIENT_ID") }}'
        secret: '{{ lookup("env", "AZ_CLIENT_SECERT") }}'
        tenant: '{{ lookup("env", "AZ_TENET_ID") }}'
 #       ad_user: "{{ ad_user }}"
 #       password: "{{ ad_password }}"
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_snap_name }}"
        location: westus
        creation_data:
          create_option: Copy
          source_id: '/subscriptions/{{az_sub_id}}/resourceGroups/{{az_resource_group}}/providers/Microsoft.Compute/disks/{{az_disk_name}}'
       

