---
- name: Create an image from os disk
  hosts: localhost #we are calling azure api from the ansible control node
  tasks:
    - name: Calling out to azure to create snapshot
      azure_rm_image:
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_snap_name }}"
        source: "{{ azure_target }}
