---
- name: Create an image from os disk
  hosts: localhost #we are calling azure api from the ansible control node
  tasks:
    - name: Calling out to azure to create snapshot
      azure_rm_image:
 #       ad_user: "{{ ad_user }}"
 #       password: "{{ ad_password }}"
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_snap_name }}"
        source: '/subscriptions/{{az_sub_id}}/resourceGroups/{{az_resource_group}}/providers/Microsoft.Compute/disks/{{az_disk_name}}'
        os_type: "{{ az_os_type }}"
