---
- name: "Checking Linux Configuration"
  hosts: linux
  vars_files:
    - vars/vault
  roles:
    - common
    - linux

- name: "Checking Database Configuration"
  hosts: linux_databases
  vars_files:
    - vars/vault
  roles:
    - databases

- name: "Checking Webserver Configuration"
  hosts: linux_webservers
  vars_files:
    - vars/vault
  roles:
    - webservers

#- name: "Checking Windows Configuration"
#  hosts: windows
#  vars_files:
#    - vars/vault
#    - vars/winrm.yml
#  roles:
#    - common
#    - windows
